{
 "title": "QMODEL",
 "time": { "from": "2009-07-27T16:07:42.199Z", "to": "2026-04-24T07:03:58.581Z" },
 "panels": [
  {
   "title": "Issues Opened",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n  CONCAT(project_owner, '_', project_project_name) AS project,\n  DATE(created_at) AS time,\n  COUNT(*) AS issues_opened\n  FROM\n  project_issue\n  GROUP BY\n  project_owner, project_project_name, DATE(created_at)\n  ORDER BY\n  DATE(created_at) ASC;"
    }
   ]
  },
  {
   "title": "Issues Closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    CONCAT(project_owner, '_', project_project_name) AS project,\n    DATE(closed_at) AS time,\n    COUNT(*) AS issues_closed\nFROM\n    project_issue\nWHERE\n    closed_at IS NOT NULL\nGROUP BY\n    project_owner, project_project_name, DATE(closed_at)\nORDER BY\n    DATE(closed_at) ASC;"
    }
   ]
  },
  {
   "title": "Total Developers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    CONCAT(p.project_owner, '_', p.project_name) AS project,\n    DATE(c.commit_date) AS time,\n    COUNT(DISTINCT c.author) AS num_developers\nFROM\n    commit c\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\n        JOIN\n    project p ON ag.project_project_owner = p.project_owner AND ag.project_project_name = p.project_name\nGROUP BY\n    p.project_owner, p.project_name, DATE(c.commit_date)\nORDER BY\n    DATE(c.commit_date) ASC;"
    }
   ]
  },
  {
   "title": "Total Developers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    ag.project_project_owner AS repo_owner,\n    ag.project_project_name AS repo_project_name,\n    COUNT(DISTINCT c.author) AS num_developers\nFROM\n    commit c\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\nGROUP BY\n    ag.project_project_owner, ag.project_project_name\nORDER BY\n    num_developers DESC;"
    }
   ]
  },
  {
   "title": "Total Deletions Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    CONCAT(p.project_owner, '_', p.project_name) AS project,\n    DATE(c.commit_date) AS time,\n    SUM(fc.total_deletions) AS total_deletions\nFROM\n    file_change fc\n        JOIN\n    commit_file_changes cfc ON fc.id = cfc.file_changes_id\n        JOIN\n    commit c ON cfc.commit_sha = c.sha\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\n        JOIN\n    project p ON ag.project_project_owner = p.project_owner AND ag.project_project_name = p.project_name\nGROUP BY\n    p.project_owner, p.project_name, c.commit_date\nORDER BY\n    c.commit_date ASC"
    }
   ]
  },
  {
   "title": "Total Deletions Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    CONCAT(p.project_owner, '_', p.project_name) AS project,\n    DATE(c.commit_date) AS time,\n    SUM(fc.total_deletions) AS total_deletions\nFROM\n    file_change fc\n        JOIN\n    commit_file_changes cfc ON fc.id = cfc.file_changes_id\n        JOIN\n    commit c ON cfc.commit_sha = c.sha\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\n        JOIN\n    project p ON ag.project_project_owner = p.project_owner AND ag.project_project_name = p.project_name\nGROUP BY\n    p.project_owner, p.project_name, c.commit_date\nORDER BY\n    c.commit_date ASC"
    }
   ]
  },
  {
   "title": "Total Changes Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    CONCAT(p.project_owner, '_', p.project_name) AS project,\n    DATE(c.commit_date) AS time,\n    SUM(fc.total_changes) AS total_changes\nFROM\n    file_change fc\n        JOIN\n    commit_file_changes cfc ON fc.id = cfc.file_changes_id\n        JOIN\n    commit c ON cfc.commit_sha = c.sha\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\n        JOIN\n    project p ON ag.project_project_owner = p.project_owner AND ag.project_project_name = p.project_name\nGROUP BY\n    p.project_owner, p.project_name, c.commit_date\nORDER BY\n    c.commit_date ASC"
    }
   ]
  },
  {
   "title": "Total Additions Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT\n    CONCAT(p.project_owner, '_', p.project_name) AS project,\n    DATE(c.commit_date) AS time,\n    SUM(fc.total_additions) AS total_additions\nFROM\n    file_change fc\n        JOIN\n    commit_file_changes cfc ON fc.id = cfc.file_changes_id\n        JOIN\n    commit c ON cfc.commit_sha = c.sha\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\n        JOIN\n    project p ON ag.project_project_owner = p.project_owner AND ag.project_project_name = p.project_name\nGROUP BY\n    p.project_owner, p.project_name, c.commit_date\nORDER BY\n    c.commit_date ASC"
    }
   ]
  },
  {
   "title": "Commit Activity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT CONCAT(p.project_owner, '_', p.project_name) AS project,\n       DATE(c.commit_date) AS time,\n       COUNT(c.sha) AS commitCount\nFROM commit c\n         JOIN agraph ag ON c.a_graph_id = ag.id\n         JOIN project p ON p.project_owner = ag.project_project_owner AND p.project_name = ag.project_project_name\nGROUP BY p.project_owner, p.project_name, time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Pull Request Review Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT CONCAT(project_owner, '_', project_project_name) AS project,\n  DATE(created_at) AS time,\n  AVG(TIMESTAMPDIFF(HOUR, created_at, closed_at)) AS avg_review_time\n  FROM project_pull\n  where project_pull.closed_at IS NOT NULL\n  GROUP BY project_owner, project_project_name, time\n  ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Issue Resolution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "dataset": "qmodel_demo",
     "rawSql": "SELECT CONCAT(project_owner, ':', project_project_name) AS project,\n  DATE(created_at) AS time,\n  AVG(TIMESTAMPDIFF(DAY, created_at, closed_at)) AS avg_review_time\n  FROM project_issue\n  where project_issue.closed_at IS NOT NULL\n  GROUP BY project_owner, project_project_name, time\n  ORDER BY time ASC;"
    }
   ]
  }
 ]
}