{
 "title": "QMODEL",
 "time": { "from": "2020-10-04T00:00:00.000Z", "to": "2023-11-19T00:00:00.000Z" },
 "panels": [
  {
   "title": "Total Deletions Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \n  CONCAT(p.owner, '_', p.project_name) AS project,\n  DATE(c.commit_date) AS time,\n  SUM(fc.total_deletions) AS total_deletions\nFROM \n  file_change fc\nJOIN \n  commit_file_changes cfc ON fc.id = cfc.file_changes_id\nJOIN \n  commit c ON cfc.commit_id = c.id\nJOIN \n  agraph ag ON c.a_graph_id = ag.id\nJOIN \n  project p ON ag.repo_owner = p.owner AND ag.repo_project_name = p.project_name\nGROUP BY \n  p.owner, p.project_name, c.commit_date\nORDER BY \n  c.commit_date ASC\n"
    }
   ]
  },
  {
   "title": "Total Changes Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \n  CONCAT(p.owner, '_', p.project_name) AS project,\n  DATE(c.commit_date) AS time,\n  SUM(fc.total_changes) AS total_changes\nFROM \n  file_change fc\nJOIN \n  commit_file_changes cfc ON fc.id = cfc.file_changes_id\nJOIN \n  commit c ON cfc.commit_id = c.id\nJOIN \n  agraph ag ON c.a_graph_id = ag.id\nJOIN \n  project p ON ag.repo_owner = p.owner AND ag.repo_project_name = p.project_name\nGROUP BY \n  p.owner, p.project_name, c.commit_date\nORDER BY \n  c.commit_date ASC\n"
    }
   ]
  },
  {
   "title": "Total Additions Per Commit Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\n    CONCAT(p.owner, '_', p.project_name) AS project,\n    DATE(c.commit_date) AS time,\n    SUM(fc.total_additions) AS total_additions\nFROM\n    file_change fc\n        JOIN\n    commit_file_changes cfc ON fc.id = cfc.file_changes_id\n        JOIN\n    commit c ON cfc.commit_id = c.id\n        JOIN\n    agraph ag ON c.a_graph_id = ag.id\n        JOIN\n    project p ON ag.repo_owner = p.owner AND ag.repo_project_name = p.project_name\nGROUP BY\n    p.owner, p.project_name, c.commit_date\nORDER BY\n    c.commit_date ASC\n"
    }
   ]
  },
  {
   "title": "Commit Activity Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT CONCAT(p.owner, '_', p.project_name) AS project,\n  DATE(c.commit_date) AS time,\n  COUNT(c.id) AS commitCount\n  FROM commit c\n  JOIN agraph ag ON c.a_graph_id = ag.id\n  JOIN project p ON p.owner = ag.repo_owner AND p.project_name = ag.repo_project_name\n  GROUP BY p.owner, p.project_name, time\n  ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Pull Request Review Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT CONCAT(project_owner, '_', project_project_name) AS project,\n  DATE(created_at) AS time,\n  AVG(TIMESTAMPDIFF(HOUR, created_at, closed_at)) AS avg_review_time\n  FROM project_pull\n  where project_pull.closed_at IS NOT NULL\n  GROUP BY project_owner, project_project_name, time\n  ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Issue Resolution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT CONCAT(project_owner, ':', project_project_name) AS project,\n  DATE(created_at) AS time,\n  AVG(TIMESTAMPDIFF(HOUR, created_at, closed_at)) AS avg_review_time\n  FROM project_issue\n  where project_issue.closed_at IS NOT NULL\n  GROUP BY project_owner, project_project_name, time\n  ORDER BY time ASC;"
    }
   ]
  }
 ]
}